services:
  backend:
    container_name: ft-transcendence-auth-service
    image: jbadaire/auth_service:latest
    restart: always
    networks:
      - ft_transcendence
    env_file:
      - .env
    volumes:
      - auth-service-vlm:/app/

  transcendence-webserver:
    container_name: ft-transcendence-webserver
    image: ghcr.io/42-transcendance-cgpsv/nginx:latest
    restart: no
    networks:
      - ft_transcendence
    ports:
      - "25565:443"
    depends_on:
      - backend

volumes:
  auth-service-vlm:
    name: auth-service-vlm
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /sgoinfre/jbadaire/data/auth_service

networks:
  ft_transcendence:
    name: transcendence
    driver: bridge
